// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using inmobiliariaApi.Data;

#nullable disable

namespace inmobiliaria_api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260408212645_AddThumbnailToImagenPropiedad")]
    partial class AddThumbnailToImagenPropiedad
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("inmobiliariaApi.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("actualizado_en");

                    b.Property<DateTime?>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Dni")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("dni");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<int>("IdInmobiliaria")
                        .HasColumnType("int")
                        .HasColumnName("id_inmobiliaria");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.HasIndex("IdInmobiliaria");

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("inmobiliariaApi.Models.EstadoInmobiliaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("estados_inmobiliaria");
                });

            modelBuilder.Entity("inmobiliariaApi.Models.EstadoLead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("estados_lead");
                });

            modelBuilder.Entity("inmobiliariaApi.Models.EstadoPropiedadActividad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Visible")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("estados_propiedad_actidad");
                });

            modelBuilder.Entity("inmobiliariaApi.Models.EstadoPropiedadOperativo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ColorHex")
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)")
                        .HasColumnName("color_hex");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("estados_propiedades_operativas");
                });

            modelBuilder.Entity("inmobiliariaApi.Models.EstadoSuscripcion", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("PermiteOperar")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("permite_operar");

                    b.HasKey("Id");

                    b.ToTable("estados_suscripcion");
                });

            modelBuilder.Entity("inmobiliariaApi.Models.EstadoUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("estados_usuario");
                });

            modelBuilder.Entity("inmobiliariaApi.Models.FuenteContacto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("fuentes_contacto");
                });

            modelBuilder.Entity("inmobiliariaApi.Models.ImagenPropiedad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creado_en");

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("es_principal");

                    b.Property<int>("IdPropiedad")
                        .HasColumnType("int")
                        .HasColumnName("id_propiedad");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<string>("R2Key")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("r2_key");

                    b.Property<string>("ThumbnailKey")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("thumbnail_key");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("thumbnail_url");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("IdPropiedad");

                    b.ToTable("imagenes_propiedades", (string)null);
                });

            modelBuilder.Entity("inmobiliariaApi.Models.Inmobiliaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("actualizado_en");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DominioPersonalizado")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("dominio_personalizado");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    b.Property<int>("IdPlan")
                        .HasColumnType("int")
                        .HasColumnName("id_plan");

                    b.Property<long?>("IdProvincia")
                        .HasColumnType("bigint")
                        .HasColumnName("id_provincia");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Subdominio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdPlan");

                    b.HasIndex("IdProvincia");

                    b.HasIndex("Subdominio")
                        .IsUnique();

                    b.ToTable("inmobiliarias");
                });

            modelBuilder.Entity("inmobiliariaApi.Models.Lead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("activo");

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("actualizado_en");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int?>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    b.Property<int>("IdFuente")
                        .HasColumnType("int")
                        .HasColumnName("id_fuente");

                    b.Property<int>("IdInmobiliaria")
                        .HasColumnType("int")
                        .HasColumnName("id_inmobiliaria");

                    b.Property<int?>("IdPropiedad")
                        .HasColumnType("int")
                        .HasColumnName("id_propiedad");

                    b.Property<int?>("IdUsuarioAsignado")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario_asignado");

                    b.Property<int?>("IdUsuarioWeb")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario_web");

                    b.Property<string>("Mensaje")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdFuente");

                    b.HasIndex("IdInmobiliaria");

                    b.HasIndex("IdPropiedad");

                    b.HasIndex("IdUsuarioAsignado");

                    b.HasIndex("IdUsuarioWeb");

                    b.ToTable("leads");
                });

            modelBuilder.Entity("inmobiliariaApi.Models.LeadEstadoHistorial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Comentario")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("IdEstadoAnterior")
                        .HasColumnType("int")
                        .HasColumnName("id_estado_anterior");

                    b.Property<int>("IdEstadoNuevo")
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    b.Property<int>("IdLead")
                        .HasColumnType("int")
                        .HasColumnName("id_lead");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.HasKey("Id");

                    b.HasIndex("IdEstadoAnterior");

                    b.HasIndex("IdEstadoNuevo");

                    b.HasIndex("IdLead");

                    b.HasIndex("IdUsuario");

                    b.ToTable("lead_estado_historial");
                });

            modelBuilder.Entity("inmobiliariaApi.Models.Localidad", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_localidad");

                    b.Property<string>("CodigoPostal")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("codigo_postal");

                    b.Property<long?>("IdPartido")
                        .HasColumnType("bigint")
                        .HasColumnName("id_partido");

                    b.Property<long>("IdProvincia")
                        .HasColumnType("bigint")
                        .HasColumnName("id_provincia");

                    b.Property<string>("Latitud")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Longitud")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Municipio")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.HasKey("Id");

                    b.HasIndex("IdProvincia");

                    b.ToTable("localidades");
                });

            modelBuilder.Entity("inmobiliariaApi.Models.PagoSuscripcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("actualizado_en");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DiasPlan")
                        .HasColumnType("int")
                        .HasColumnName("dias_plan");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("estado");

                    b.Property<int>("IdInmobiliaria")
                        .HasColumnType("int")
                        .HasColumnName("id_inmobiliaria");

                    b.Property<int>("IdPlan")
                        .HasColumnType("int")
                        .HasColumnName("id_plan");

                    b.Property<int?>("IdSuscripcion")
                        .HasColumnType("int")
                        .HasColumnName("id_suscripcion");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("moneda");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("monto");

                    b.Property<long?>("MpPaymentId")
                        .HasColumnType("bigint")
                        .HasColumnName("mp_payment_id");

                    b.Property<string>("MpPreferenceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("mp_preference_id");

                    b.HasKey("Id");

                    b.HasIndex("IdPlan");

                    b.HasIndex("IdSuscripcion");

                    b.HasIndex("MpPreferenceId");

                    b.HasIndex("IdInmobiliaria", "Estado");

                    b.ToTable("pagos_suscripcion");
                });

            modelBuilder.Entity("inmobiliariaApi.Models.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("ActividadesLead")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("actividades_lead");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("actualizado_en");

                    b.Property<bool>("ApiAcceso")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("api_acceso");

                    b.Property<bool>("AutomatizacionLeads")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("automatizacion_leads");

                    b.Property<bool>("Automatizaciones")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creado_en");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("DominioPersonalizado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("dominio_personalizado");

                    b.Property<bool>("HistorialEstados")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("historial_estados");

                    b.Property<bool>("LeadScoring")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("lead_scoring");

                    b.Property<int?>("MaxImagenesPropiedad")
                        .HasColumnType("int")
                        .HasColumnName("max_imagenes_propiedad");

                    b.Property<int?>("MaxLeadsMes")
                        .HasColumnType("int")
                        .HasColumnName("max_leads_mes");

                    b.Property<int?>("MaxPropiedades")
                        .HasColumnType("int")
                        .HasColumnName("max_propiedades");

                    b.Property<int?>("MaxUsuarios")
                        .HasColumnType("int")
                        .HasColumnName("max_usuarios");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("PrecioUsd")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio_usd");

                    b.Property<string>("Soporte")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TiposActividad")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("tipos_actividad");

                    b.Property<bool>("WhiteLabel")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("white_label");

                    b.HasKey("Id");

                    b.ToTable("planes");
                });

            modelBuilder.Entity("inmobiliariaApi.Models.Propiedad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("actualizado_en");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("EsPublicada")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("es_publicada");

                    b.Property<int?>("IdAgenteResponsable")
                        .HasColumnType("int")
                        .HasColumnName("id_agente_responsable");

                    b.Property<int>("IdEstadoAdmin")
                        .HasColumnType("int")
                        .HasColumnName("id_estado_admin");

                    b.Property<int>("IdEstadoOperativo")
                        .HasColumnType("int")
                        .HasColumnName("id_estado_operativo");

                    b.Property<int>("IdInmobiliaria")
                        .HasColumnType("int")
                        .HasColumnName("id_inmobiliaria");

                    b.Property<long?>("IdLocalidad")
                        .HasColumnType("bigint")
                        .HasColumnName("id_localidad");

                    b.Property<decimal?>("Latitud")
                        .HasColumnType("decimal(10,8)");

                    b.Property<decimal?>("Longitud")
                        .HasColumnType("decimal(10,8)");

                    b.Property<decimal?>("Precio")
                        .HasColumnType("decimal(15,2)");

                    b.Property<DateTime?>("PublicadaEn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("publicada_en");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("IdAgenteResponsable");

                    b.HasIndex("IdEstadoAdmin");

                    b.HasIndex("IdEstadoOperativo");

                    b.HasIndex("IdInmobiliaria");

                    b.HasIndex("IdLocalidad");

                    b.ToTable("propiedades");
                });

            modelBuilder.Entity("inmobiliariaApi.Models.PropiedadFavorita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creado_en");

                    b.Property<int>("IdPropiedad")
                        .HasColumnType("int")
                        .HasColumnName("id_propiedad");

                    b.Property<int>("IdUsuarioWeb")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario_web");

                    b.HasKey("Id");

                    b.HasIndex("IdPropiedad");

                    b.HasIndex("IdUsuarioWeb");

                    b.ToTable("propiedades_favoritas");
                });

            modelBuilder.Entity("inmobiliariaApi.Models.Provincia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_provincia");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CodigoIndec")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("codigo_indec");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.HasKey("Id");

                    b.ToTable("provincias");
                });

            modelBuilder.Entity("inmobiliariaApi.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("ExpiraEn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expira_en");

                    b.Property<int>("IdInmobiliaria")
                        .HasColumnType("int")
                        .HasColumnName("id_inmobiliaria");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<string>("IpOrigen")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("ip_origen");

                    b.Property<string>("ReemplazadoPor")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("reemplazado_por");

                    b.Property<DateTime?>("RevocadoEn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("revocado_en");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("IdUsuario", "RevocadoEn");

                    b.ToTable("refresh_tokens");
                });

            modelBuilder.Entity("inmobiliariaApi.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("inmobiliariaApi.Models.Suscripcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("actualizado_en");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creado_en");

                    b.Property<DateTime>("Fin")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fin");

                    b.Property<byte>("IdEstado")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("id_estado");

                    b.Property<int>("IdInmobiliaria")
                        .HasColumnType("int")
                        .HasColumnName("id_inmobiliaria");

                    b.Property<int>("IdPlan")
                        .HasColumnType("int")
                        .HasColumnName("id_plan");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("inicio");

                    b.Property<bool>("RenovacionAutomatica")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("renovacion_automatica");

                    b.HasKey("Id");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdInmobiliaria");

                    b.HasIndex("IdPlan");

                    b.ToTable("suscripciones");
                });

            modelBuilder.Entity("inmobiliariaApi.Models.TipoTransaccion", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("activo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("tipo_transaccion");
                });

            modelBuilder.Entity("inmobiliariaApi.Models.TransaccionHistorial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creado_en");

                    b.Property<DateTime?>("FechaOperacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_operacion");

                    b.Property<int?>("IdAgente")
                        .HasColumnType("int")
                        .HasColumnName("id_agente");

                    b.Property<int?>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    b.Property<int?>("IdInmobiliaria")
                        .HasColumnType("int")
                        .HasColumnName("id_inmobiliaria");

                    b.Property<int?>("IdPropiedad")
                        .HasColumnType("int")
                        .HasColumnName("id_propiedad");

                    b.Property<byte?>("IdTipoTransaccion")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("id_tipo_transaccion");

                    b.Property<string>("Observaciones")
                        .HasColumnType("longtext")
                        .HasColumnName("observaciones");

                    b.Property<decimal?>("Precio")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("precio");

                    b.HasKey("Id");

                    b.HasIndex("IdAgente");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdInmobiliaria");

                    b.HasIndex("IdPropiedad");

                    b.HasIndex("IdTipoTransaccion");

                    b.ToTable("transacciones_historial");
                });

            modelBuilder.Entity("inmobiliariaApi.Models.UsoMensual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("actualizado_en");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creado_en");

                    b.Property<int>("IdInmobiliaria")
                        .HasColumnType("int")
                        .HasColumnName("id_inmobiliaria");

                    b.Property<int>("LeadsGenerados")
                        .HasColumnType("int")
                        .HasColumnName("leads_generados");

                    b.Property<string>("Mes")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)");

                    b.HasKey("Id");

                    b.HasIndex("IdInmobiliaria");

                    b.ToTable("uso_mensual");
                });

            modelBuilder.Entity("inmobiliariaApi.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("actualizado_en");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creado_en");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("HashContrasena")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("hash_contrasena");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    b.Property<int>("IdInmobiliaria")
                        .HasColumnType("int")
                        .HasColumnName("id_inmobiliaria");

                    b.Property<int>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdInmobiliaria");

                    b.HasIndex("IdRol");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("inmobiliariaApi.Models.UsuarioWeb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("activo");

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("actualizado_en");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creado_en");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("EmailVerificado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("email_verificado");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("google_id");

                    b.Property<string>("HashContrasena")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("hash_contrasena");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ProveedorAuth")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("proveedor_auth");

                    b.HasKey("Id");

                    b.ToTable("usuarios_web");
                });

            modelBuilder.Entity("inmobiliariaApi.Models.Cliente", b =>
                {
                    b.HasOne("inmobiliariaApi.Models.Inmobiliaria", "Inmobiliaria")
                        .WithMany()
                        .HasForeignKey("IdInmobiliaria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Inmobiliaria");
                });

            modelBuilder.Entity("inmobiliariaApi.Models.ImagenPropiedad", b =>
                {
                    b.HasOne("inmobiliariaApi.Models.Propiedad", "Propiedad")
                        .WithMany("Imagenes")
                        .HasForeignKey("IdPropiedad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Propiedad");
                });

            modelBuilder.Entity("inmobiliariaApi.Models.Inmobiliaria", b =>
                {
                    b.HasOne("inmobiliariaApi.Models.EstadoInmobiliaria", "Estado")
                        .WithMany("Inmobiliarias")
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("inmobiliariaApi.Models.Plan", "Plan")
                        .WithMany("Inmobiliarias")
                        .HasForeignKey("IdPlan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("inmobiliariaApi.Models.Provincia", "Provincia")
                        .WithMany("Inmobiliarias")
                        .HasForeignKey("IdProvincia")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Estado");

                    b.Navigation("Plan");

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("inmobiliariaApi.Models.Lead", b =>
                {
                    b.HasOne("inmobiliariaApi.Models.Cliente", "Cliente")
                        .WithMany("Leads")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("inmobiliariaApi.Models.EstadoLead", "Estado")
                        .WithMany("Leads")
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("inmobiliariaApi.Models.FuenteContacto", "Fuente")
                        .WithMany("Leads")
                        .HasForeignKey("IdFuente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("inmobiliariaApi.Models.Inmobiliaria", "Inmobiliaria")
                        .WithMany("Leads")
                        .HasForeignKey("IdInmobiliaria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("inmobiliariaApi.Models.Propiedad", "Propiedad")
                        .WithMany("Leads")
                        .HasForeignKey("IdPropiedad")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("inmobiliariaApi.Models.Usuario", "UsuarioAsignado")
                        .WithMany("LeadsAsignados")
                        .HasForeignKey("IdUsuarioAsignado")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("inmobiliariaApi.Models.UsuarioWeb", "UsuarioWeb")
                        .WithMany("LeadsEnviados")
                        .HasForeignKey("IdUsuarioWeb");

                    b.Navigation("Cliente");

                    b.Navigation("Estado");

                    b.Navigation("Fuente");

                    b.Navigation("Inmobiliaria");

                    b.Navigation("Propiedad");

                    b.Navigation("UsuarioAsignado");

                    b.Navigation("UsuarioWeb");
                });

            modelBuilder.Entity("inmobiliariaApi.Models.LeadEstadoHistorial", b =>
                {
                    b.HasOne("inmobiliariaApi.Models.EstadoLead", "EstadoAnterior")
                        .WithMany("HistorialEstadosAnteriores")
                        .HasForeignKey("IdEstadoAnterior")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("inmobiliariaApi.Models.EstadoLead", "EstadoNuevo")
                        .WithMany("HistorialEstadosNuevos")
                        .HasForeignKey("IdEstadoNuevo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("inmobiliariaApi.Models.Lead", "Lead")
                        .WithMany("HistorialEstados")
                        .HasForeignKey("IdLead")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("inmobiliariaApi.Models.Usuario", "Usuario")
                        .WithMany("CambiosEstadoLead")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EstadoAnterior");

                    b.Navigation("EstadoNuevo");

                    b.Navigation("Lead");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("inmobiliariaApi.Models.Localidad", b =>
                {
                    b.HasOne("inmobiliariaApi.Models.Provincia", "Provincia")
                        .WithMany("Localidades")
                        .HasForeignKey("IdProvincia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("inmobiliariaApi.Models.PagoSuscripcion", b =>
                {
                    b.HasOne("inmobiliariaApi.Models.Inmobiliaria", "Inmobiliaria")
                        .WithMany()
                        .HasForeignKey("IdInmobiliaria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("inmobiliariaApi.Models.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("IdPlan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("inmobiliariaApi.Models.Suscripcion", "Suscripcion")
                        .WithMany()
                        .HasForeignKey("IdSuscripcion")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Inmobiliaria");

                    b.Navigation("Plan");

                    b.Navigation("Suscripcion");
                });

            modelBuilder.Entity("inmobiliariaApi.Models.Propiedad", b =>
                {
                    b.HasOne("inmobiliariaApi.Models.Usuario", "AgenteResponsable")
                        .WithMany("PropiedadesResponsable")
                        .HasForeignKey("IdAgenteResponsable")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("inmobiliariaApi.Models.EstadoPropiedadActividad", "EstadoAdmin")
                        .WithMany("Propiedades")
                        .HasForeignKey("IdEstadoAdmin")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("inmobiliariaApi.Models.EstadoPropiedadOperativo", "EstadoOperativo")
                        .WithMany("Propiedades")
                        .HasForeignKey("IdEstadoOperativo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("inmobiliariaApi.Models.Inmobiliaria", "Inmobiliaria")
                        .WithMany("Propiedades")
                        .HasForeignKey("IdInmobiliaria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("inmobiliariaApi.Models.Localidad", "Localidad")
                        .WithMany("Propiedades")
                        .HasForeignKey("IdLocalidad")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AgenteResponsable");

                    b.Navigation("EstadoAdmin");

                    b.Navigation("EstadoOperativo");

                    b.Navigation("Inmobiliaria");

                    b.Navigation("Localidad");
                });

            modelBuilder.Entity("inmobiliariaApi.Models.PropiedadFavorita", b =>
                {
                    b.HasOne("inmobiliariaApi.Models.Propiedad", "Propiedad")
                        .WithMany()
                        .HasForeignKey("IdPropiedad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("inmobiliariaApi.Models.UsuarioWeb", "UsuarioWeb")
                        .WithMany("Favoritos")
                        .HasForeignKey("IdUsuarioWeb")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Propiedad");

                    b.Navigation("UsuarioWeb");
                });

            modelBuilder.Entity("inmobiliariaApi.Models.RefreshToken", b =>
                {
                    b.HasOne("inmobiliariaApi.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("inmobiliariaApi.Models.Suscripcion", b =>
                {
                    b.HasOne("inmobiliariaApi.Models.EstadoSuscripcion", "Estado")
                        .WithMany("Suscripciones")
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("inmobiliariaApi.Models.Inmobiliaria", "Inmobiliaria")
                        .WithMany()
                        .HasForeignKey("IdInmobiliaria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("inmobiliariaApi.Models.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("IdPlan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("Inmobiliaria");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("inmobiliariaApi.Models.TransaccionHistorial", b =>
                {
                    b.HasOne("inmobiliariaApi.Models.Usuario", "Agente")
                        .WithMany("TransaccionesHistorial")
                        .HasForeignKey("IdAgente");

                    b.HasOne("inmobiliariaApi.Models.Cliente", "Cliente")
                        .WithMany("TransaccionesHistorial")
                        .HasForeignKey("IdCliente");

                    b.HasOne("inmobiliariaApi.Models.Inmobiliaria", "Inmobiliaria")
                        .WithMany("TransaccionesHistorial")
                        .HasForeignKey("IdInmobiliaria");

                    b.HasOne("inmobiliariaApi.Models.Propiedad", "Propiedad")
                        .WithMany("TransaccionesHistorial")
                        .HasForeignKey("IdPropiedad");

                    b.HasOne("inmobiliariaApi.Models.TipoTransaccion", "TipoTransaccion")
                        .WithMany("TransaccionesHistorial")
                        .HasForeignKey("IdTipoTransaccion");

                    b.Navigation("Agente");

                    b.Navigation("Cliente");

                    b.Navigation("Inmobiliaria");

                    b.Navigation("Propiedad");

                    b.Navigation("TipoTransaccion");
                });

            modelBuilder.Entity("inmobiliariaApi.Models.UsoMensual", b =>
                {
                    b.HasOne("inmobiliariaApi.Models.Inmobiliaria", "Inmobiliaria")
                        .WithMany()
                        .HasForeignKey("IdInmobiliaria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inmobiliaria");
                });

            modelBuilder.Entity("inmobiliariaApi.Models.Usuario", b =>
                {
                    b.HasOne("inmobiliariaApi.Models.EstadoUsuario", "Estado")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("inmobiliariaApi.Models.Inmobiliaria", "Inmobiliaria")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdInmobiliaria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("inmobiliariaApi.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("Inmobiliaria");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("inmobiliariaApi.Models.Cliente", b =>
                {
                    b.Navigation("Leads");

                    b.Navigation("TransaccionesHistorial");
                });

            modelBuilder.Entity("inmobiliariaApi.Models.EstadoInmobiliaria", b =>
                {
                    b.Navigation("Inmobiliarias");
                });

            modelBuilder.Entity("inmobiliariaApi.Models.EstadoLead", b =>
                {
                    b.Navigation("HistorialEstadosAnteriores");

                    b.Navigation("HistorialEstadosNuevos");

                    b.Navigation("Leads");
                });

            modelBuilder.Entity("inmobiliariaApi.Models.EstadoPropiedadActividad", b =>
                {
                    b.Navigation("Propiedades");
                });

            modelBuilder.Entity("inmobiliariaApi.Models.EstadoPropiedadOperativo", b =>
                {
                    b.Navigation("Propiedades");
                });

            modelBuilder.Entity("inmobiliariaApi.Models.EstadoSuscripcion", b =>
                {
                    b.Navigation("Suscripciones");
                });

            modelBuilder.Entity("inmobiliariaApi.Models.EstadoUsuario", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("inmobiliariaApi.Models.FuenteContacto", b =>
                {
                    b.Navigation("Leads");
                });

            modelBuilder.Entity("inmobiliariaApi.Models.Inmobiliaria", b =>
                {
                    b.Navigation("Leads");

                    b.Navigation("Propiedades");

                    b.Navigation("TransaccionesHistorial");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("inmobiliariaApi.Models.Lead", b =>
                {
                    b.Navigation("HistorialEstados");
                });

            modelBuilder.Entity("inmobiliariaApi.Models.Localidad", b =>
                {
                    b.Navigation("Propiedades");
                });

            modelBuilder.Entity("inmobiliariaApi.Models.Plan", b =>
                {
                    b.Navigation("Inmobiliarias");
                });

            modelBuilder.Entity("inmobiliariaApi.Models.Propiedad", b =>
                {
                    b.Navigation("Imagenes");

                    b.Navigation("Leads");

                    b.Navigation("TransaccionesHistorial");
                });

            modelBuilder.Entity("inmobiliariaApi.Models.Provincia", b =>
                {
                    b.Navigation("Inmobiliarias");

                    b.Navigation("Localidades");
                });

            modelBuilder.Entity("inmobiliariaApi.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("inmobiliariaApi.Models.TipoTransaccion", b =>
                {
                    b.Navigation("TransaccionesHistorial");
                });

            modelBuilder.Entity("inmobiliariaApi.Models.Usuario", b =>
                {
                    b.Navigation("CambiosEstadoLead");

                    b.Navigation("LeadsAsignados");

                    b.Navigation("PropiedadesResponsable");

                    b.Navigation("TransaccionesHistorial");
                });

            modelBuilder.Entity("inmobiliariaApi.Models.UsuarioWeb", b =>
                {
                    b.Navigation("Favoritos");

                    b.Navigation("LeadsEnviados");
                });
#pragma warning restore 612, 618
        }
    }
}
