// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using inmobiliariaApi.Data;

#nullable disable

namespace inmobiliaria_api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260328233500_AddR2ImageFields")]
    partial class AddR2ImageFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            // This is a minimal snapshot to allow the migration to be discovered
            // The actual snapshot is maintained in ApplicationDbContextModelSnapshot.cs
#pragma warning restore 612, 618
        }
    }
}
