// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using inmobiliariaApi.Data;

#nullable disable

namespace inmobiliaria_api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260324000001_AddEsPublicadaToPropiedad")]
    partial class AddEsPublicadaToPropiedad
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            // Snapshot simplified
            modelBuilder.Entity("inmobiliariaApi.Models.Propiedad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("EsPublicada")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("es_publicada");

                    b.HasKey("Id");

                    b.ToTable("propiedades", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
