// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using inmobiliariaApi.Data;

#nullable disable

namespace inmobiliaria_api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            // Auto increment columns

            modelBuilder.Entity("inmobiliariaApi.Models.Propiedad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    // Single byte identity

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("actualizado_en");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creado_en");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("EsPublicada")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("es_publicada");

                    b.Property<int?>("IdAgenteResponsable")
                        .HasColumnType("int")
                        .HasColumnName("id_agente_responsable");

                    b.Property<int>("IdEstadoAdmin")
                        .HasColumnType("int")
                        .HasColumnName("id_estado_admin");

                    b.Property<int>("IdEstadoOperativo")
                        .HasColumnType("int")
                        .HasColumnName("id_estado_operativo");

                    b.Property<int>("IdInmobiliaria")
                        .HasColumnType("int")
                        .HasColumnName("id_inmobiliaria");

                    b.Property<long?>("IdLocalidad")
                        .HasColumnType("bigint")
                        .HasColumnName("id_localidad");

                    b.Property<decimal?>("Latitud")
                        .HasColumnType("decimal(10,8)")
                        .HasColumnName("latitud");

                    b.Property<decimal?>("Longitud")
                        .HasColumnType("decimal(10,8)")
                        .HasColumnName("longitud");

                    b.Property<decimal?>("Precio")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("precio");

                    b.Property<DateTime?>("PublicadaEn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("publicada_en");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.ToTable("propiedades", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
